"""Generate web/src/lib/metro.ts from the Python metro registry.

Keeps the TypeScript metro config in sync with the Python source of truth,
eliminating manual duplication.
"""

import json
from pathlib import Path

from urbanstack.metro import METRO_REGISTRY, REGION_CONFIGS

_HEADER = """\
// AUTO-GENERATED by pipeline/src/urbanstack/sync_web.py
// do not edit manually — run `uv run python -m urbanstack.sync_web` to regenerate
"""


def _fmt_center(center: tuple[float, float]) -> str:
    """Format a (lat, lon) tuple as a TypeScript array literal."""
    lat, lon = center
    return f"[{lat}, {lon}]"


def generate_metro_ts() -> str:
    """Build the full TypeScript source for metro.ts."""
    lines: list[str] = [_HEADER]

    # MetroConfig interface
    lines.append("export interface MetroConfig {")
    lines.append("  metro_id: string;")
    lines.append("  metro_name: string;")
    lines.append("  center: [number, number];")
    lines.append("  zoom: number;")
    lines.append("}")
    lines.append("")

    # METROS const — sorted alphabetically
    lines.append("export const METROS: Record<string, MetroConfig> = {")
    for metro_id in sorted(METRO_REGISTRY):
        m = METRO_REGISTRY[metro_id]
        lines.append(f"  {metro_id}: {{")
        lines.append(f"    metro_id: {json.dumps(m.metro_id)},")
        lines.append(f"    metro_name: {json.dumps(m.metro_name)},")
        lines.append(f"    center: {_fmt_center(m.center)},")
        lines.append(f"    zoom: {m.zoom},")
        lines.append("  },")
    lines.append("};")
    lines.append("")

    # RegionConfig interface
    lines.append("export interface RegionConfig {")
    lines.append("  region_id: string;")
    lines.append("  region_name: string;")
    lines.append("  metro_ids: string[];")
    lines.append("  center: [number, number];")
    lines.append("  zoom: number;")
    lines.append("}")
    lines.append("")

    # REGIONS const — derive metro_ids from METRO_REGISTRY
    region_metros: dict[str, list[str]] = {r: [] for r in REGION_CONFIGS}
    for metro_id in sorted(METRO_REGISTRY):
        region = METRO_REGISTRY[metro_id].region
        if region in region_metros:
            region_metros[region].append(metro_id)

    lines.append("export const REGIONS: Record<string, RegionConfig> = {")
    for region_id in sorted(REGION_CONFIGS):
        rc = REGION_CONFIGS[region_id]
        metro_ids_str = ", ".join(json.dumps(mid) for mid in region_metros[region_id])
        lines.append(f"  {region_id}: {{")
        lines.append(f"    region_id: {json.dumps(region_id)},")
        lines.append(f"    region_name: {json.dumps(rc.region_name)},")
        lines.append(f"    metro_ids: [{metro_ids_str}],")
        lines.append(f"    center: {_fmt_center(rc.center)},")
        lines.append(f"    zoom: {rc.zoom},")
        lines.append("  },")
    lines.append("};")
    lines.append("")

    # METRO_TO_REGION loop
    lines.append("export const METRO_TO_REGION: Record<string, string> = {};")
    lines.append("for (const [regionId, config] of Object.entries(REGIONS)) {")
    lines.append("  for (const metroId of config.metro_ids) {")
    lines.append("    METRO_TO_REGION[metroId] = regionId;")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def sync_web(web_root: Path) -> None:
    """Write the generated metro.ts to the web project."""
    target = web_root / "src" / "lib" / "metro.ts"
    content = generate_metro_ts()
    target.write_text(content)
    print(f"Wrote {target}")


if __name__ == "__main__":
    # Default: assume running from repo root or pipeline/
    repo_root = Path(__file__).resolve().parents[3]
    web_root = repo_root / "web"
    if not web_root.exists():
        raise FileNotFoundError(f"web/ not found at {web_root}")
    sync_web(web_root)
