// AUTO-GENERATED by pipeline/src/urbanstack/sync_web.py
// do not edit manually — run `uv run python -m urbanstack.sync_web` to regenerate

export interface MetroConfig {
  metro_id: string;
  metro_name: string;
  center: [number, number];
  zoom: number;
}

export const METROS: Record<string, MetroConfig> = {
  austin: {
    metro_id: "austin",
    metro_name: "Austin-Round Rock-San Marcos MSA",
    center: [30.27, -97.74],
    zoom: 9,
  },
  baltimore: {
    metro_id: "baltimore",
    metro_name: "Baltimore-Columbia-Towson MSA",
    center: [39.29, -76.61],
    zoom: 9,
  },
  boston: {
    metro_id: "boston",
    metro_name: "Boston-Cambridge-Newton MSA",
    center: [42.36, -71.06],
    zoom: 8,
  },
  cheyenne: {
    metro_id: "cheyenne",
    metro_name: "Cheyenne MSA",
    center: [41.14, -104.82],
    zoom: 10,
  },
  chicago: {
    metro_id: "chicago",
    metro_name: "Chicago-Naperville-Elgin MSA",
    center: [41.88, -87.63],
    zoom: 8,
  },
  dc: {
    metro_id: "dc",
    metro_name: "Washington-Arlington-Alexandria MSA",
    center: [38.9, -77.04],
    zoom: 8,
  },
  denver: {
    metro_id: "denver",
    metro_name: "Denver-Aurora-Centennial MSA",
    center: [39.74, -104.99],
    zoom: 8,
  },
  dfw: {
    metro_id: "dfw",
    metro_name: "Dallas-Fort Worth-Arlington MSA",
    center: [32.78, -96.85],
    zoom: 8,
  },
  houston: {
    metro_id: "houston",
    metro_name: "Houston-Pasadena-The Woodlands MSA",
    center: [29.76, -95.37],
    zoom: 8,
  },
  msp: {
    metro_id: "msp",
    metro_name: "Minneapolis-St. Paul-Bloomington MSA",
    center: [44.98, -93.27],
    zoom: 8,
  },
  nyc: {
    metro_id: "nyc",
    metro_name: "New York-Newark-Jersey City MSA",
    center: [40.71, -74.0],
    zoom: 8,
  },
  philadelphia: {
    metro_id: "philadelphia",
    metro_name: "Philadelphia-Camden-Wilmington MSA",
    center: [39.95, -75.16],
    zoom: 8,
  },
  portland: {
    metro_id: "portland",
    metro_name: "Portland-Vancouver-Hillsboro MSA",
    center: [45.52, -122.68],
    zoom: 8,
  },
  richmond: {
    metro_id: "richmond",
    metro_name: "Richmond MSA",
    center: [37.54, -77.44],
    zoom: 9,
  },
  san_antonio: {
    metro_id: "san_antonio",
    metro_name: "San Antonio-New Braunfels MSA",
    center: [29.42, -98.49],
    zoom: 9,
  },
};

export interface RegionConfig {
  region_id: string;
  region_name: string;
  metro_ids: string[];
  center: [number, number];
  zoom: number;
}

export const REGIONS: Record<string, RegionConfig> = {
  mid_atlantic: {
    region_id: "mid_atlantic",
    region_name: "Mid-Atlantic",
    metro_ids: ["baltimore", "dc", "richmond"],
    center: [38.6, -77.2],
    zoom: 7,
  },
  midwest: {
    region_id: "midwest",
    region_name: "Midwest",
    metro_ids: ["chicago", "msp"],
    center: [41.88, -87.63],
    zoom: 7,
  },
  mountain: {
    region_id: "mountain",
    region_name: "Mountain",
    metro_ids: ["cheyenne", "denver"],
    center: [40.44, -104.9],
    zoom: 7,
  },
  northeast: {
    region_id: "northeast",
    region_name: "Northeast",
    metro_ids: ["boston", "nyc", "philadelphia"],
    center: [41.5, -72.5],
    zoom: 6,
  },
  pacific_northwest: {
    region_id: "pacific_northwest",
    region_name: "Pacific Northwest",
    metro_ids: ["portland"],
    center: [45.52, -122.68],
    zoom: 7,
  },
  texas: {
    region_id: "texas",
    region_name: "Texas",
    metro_ids: ["austin", "dfw", "houston", "san_antonio"],
    center: [30.5, -97.0],
    zoom: 6,
  },
};

export const METRO_TO_REGION: Record<string, string> = {};
for (const [regionId, config] of Object.entries(REGIONS)) {
  for (const metroId of config.metro_ids) {
    METRO_TO_REGION[metroId] = regionId;
  }
}
